# Generated by Django 2.0.5 on 2018-05-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectemployee',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='projectemployee',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(to='manager.Employee'),
        ),
        migrations.DeleteModel(
            name='ProjectEmployee',
        ),
    ]
